import "./Home/home.css";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import StoreProvider from "./StoreProvider";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ weight: ["300", "400", "500", "700"], subsets: ["latin"], display: "swap" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
